### ISSUE TITLE
Claim Validator with PrimitiveClaim not working

### ISSUE THREAD

**Issue by omer9564** [supertokens/supertokens-python#336] opened 2023-06-04 08:23 UTC
I Have PrimitiveClaim I want to validate with the key "active_tenant"
I saw PrimitiveClaim override the function 
```
def get_value_from_payload(
        self, payload: JSONObject, user_context: Union[Dict[str, Any], None] = None
    ) -> Union[Primitive, None]:
        _ = user_context

        return payload.get(self.key, {}).get("v")
```
this function assumes payload.get(self.key,{}) returns a dict, but the value is string.
result is:
```
    return payload.get(self.key, {}).get("v")
           │       │   │    └ 'active_tenant'
           │       │   └ <supertokens_python.recipe.session.claim_base_classes.primitive_claim.PrimitiveClaim object at 0x11f1e3e20>
           │       └ <method 'get' of 'dict' objects>
           └ {'sub': '3e74de27-28a3-4feb-98f1-422ab15f61f8', 'exp': 1685868610, 'iat': 1685865010, 'sessionHandle': 'de89811b-e6b4-490d-9e...

AttributeError: 'str' object has no attribute 'get'
```

**Comment by KShivendu** [comment] 2023-06-05 06:18
Hi @omer9564, thanks for reporting.  I'll take a look. Give me some time, I'll get back to you :)

**Comment by KShivendu** [comment] 2023-06-05 06:24
So @omer9564, primitive claims are supposed to have this type:
```ts
{
 v: Primitive,
 t: number,
}
```
so `payload.get(self.key, {}).get("v")`  is correct. We have used it in email verification claim if you want a reference. 

Can you share how you're defining your primitive claim?

**Comment by omer9564** [comment] 2023-06-06 08:26
This is my session override_function:
```
ACCESS_TOKEN_TENANT_KEY: Final[str] = "active_tenant"

TenantClaim = PrimitiveClaim(
    key=ACCESS_TOKEN_TENANT_KEY,
    fetch_value=lambda key, claims: claims.get(key),
)


def override_functions(original_implementation: RecipeInterface):
    original_implementation_create_new_session = (
        original_implementation.create_new_session
    )

    def get_global_claim_validators(
        user_id: str,
        claim_validators_added_by_other_recipes: list[SessionClaimValidator],
        user_context: Dict[str, Any],
    ):
        claim_validators_added_by_other_recipes.append(
        TenantClaim.validators.has_value(str)
        )
        return claim_validators_added_by_other_recipes

    async def create_new_session(
        user_id: str,
        access_token_payload: dict[str, Any] | None,
        session_data_in_database: dict[str, Any] | None,
        disable_anti_csrf: bool | None,
        user_context: dict[str, Any],
    ):
        if access_token_payload is None:
            access_token_payload = {}

        # This goes in the access token, and is available to read on the frontend.
        access_token_payload[
            ACCESS_TOKEN_TENANT_KEY
        ] = <some-uuid>

        return await original_implementation_create_new_session(
            user_id,
            access_token_payload,
            session_data_in_database,
            disable_anti_csrf,
            user_context,
        )

    original_implementation.get_global_claim_validators = get_global_claim_validators
    original_implementation.create_new_session = create_new_session
    return original_implementation
```

I'm not sure I configured everything correctly with the claim validator, I couldn't find the part in the docs for this

**Comment by KShivendu** [comment] 2023-06-06 15:26
```python
TenantClaim = PrimitiveClaim(
    key=ACCESS_TOKEN_TENANT_KEY,
    fetch_value=lambda key, claims: claims.get(key),
)
```

Okay so basically, fetch_value will recieve `(user_id, user_context)` as input not `(key, claims)`

Can you tell me what exactly do you want to do? 

If you want to have supertokens configured such that only users with a certain value of `active-tenant` will be allowed to access the protected routes, then here's what you can do:
```python
TENANT_CLAIM_KEY: Final[str] = "active-tenant"

def tenant_fetch_value(user_id: str, user_context: Dict[str, Any]):
    return "define-this-func-to-fetch-data-based-on-user-id"

TenantClaim = PrimitiveClaim(
    key=TENANT_CLAIM_KEY,
    fetch_value=tenant_fetch_value,
    # default_max_age_in_sec=300 # set this if you want to re-fetch value at certain intervals
)

def override_functions(original_implementation: RecipeInterface):
    original_implementation_create_new_session = (
        original_implementation.create_new_session
    )

    def get_global_claim_validators(
        user_id: str,
        claim_validators_added_by_other_recipes: list[SessionClaimValidator],
        user_context: Dict[str, Any],
    ):
        claim_validators_added_by_other_recipes.append(
           TenantClaim.validators.has_value(str)
        )
        return claim_validators_added_by_other_recipes

    async def create_new_session(
        user_id: str,
        access_token_payload: dict[str, Any] | None,
        session_data_in_database: dict[str, Any] | None,
        disable_anti_csrf: bool | None,
        user_context: dict[str, Any],
    ):
        session = await original_implementation_create_new_session(
            user_id,
            access_token_payload,
            session_data_in_database,
            disable_anti_csrf,
            user_context,
        )
       
        await session.fetch_and_set_claim(TenantClaim)
        # you can also force set a certain value by using:
        # s.set_claim_value(TenantClaim, "new-value")
        # this new value won't get overridden unless 
        # you've used the default_max_age param
        # while defining the claim 
        
        return session

    original_implementation.get_global_claim_validators = get_global_claim_validators
    original_implementation.create_new_session = create_new_session
    return original_implementation
```

Let me know if you have any other quesetions.

**Comment by omer9564** [comment] 2023-06-07 08:48
Thanks @KShivendu 
It partially worked 😅 
The payload was updated using the fetcher.
I got two other problems now, which sources from the same reason:

1. Exception here https://github.com/supertokens/supertokens-python/blob/master/supertokens_python/recipe/session/utils.py#L512 
```
  File "../site-packages/supertokens_python/recipe/session/recipe.py", line 358, in verify_session
    return await self.api_implementation.verify_session(
                 │    │                  └ <function APIImplementation.verify_session at 0x12c74d6c0>
                 │    └ <supertokens_python.recipe.session.api.implementation.APIImplementation object at 0x12c736f80>
                 └ <supertokens_python.recipe.session.recipe.SessionRecipe object at 0x12c7362f0>
  File "../site-packages/supertokens_python/recipe/session/api/implementation.py", line 88, in verify_session
    return await get_session_from_request(
                 └ <function get_session_from_request at 0x107b8c1f0>
  File "../site-packages/supertokens_python/recipe/session/session_request_functions.py", line 188, in get_session_from_request
    await session.assert_claims(claim_validators, user_context)
          │       │             │                 └ {'_default': {'request': <supertokens_python.framework.fastapi.fastapi_request.FastApiRequest object at 0x12c8b1270>}}
          │       │             └ [<supertokens_python.recipe.session.claim_base_classes.primitive_claim.HasValueSCV object at 0x12c8b2b00>]
          │       └ <function Session.assert_claims at 0x107b66f80>
          └ <supertokens_python.recipe.session.session_class.Session object at 0x12c8b22f0>
  File "../site-packages/supertokens_python/recipe/session/session_class.py", line 196, in assert_claims
    validate_claim_res = await self.recipe_implementation.validate_claims(
                               │    │                     └ <function RecipeImplementation.validate_claims at 0x107b67370>
                               │    └ <supertokens_python.recipe.session.recipe_implementation.RecipeImplementation object at 0x12c736f50>
                               └ <supertokens_python.recipe.session.session_class.Session object at 0x12c8b22f0>
  File "../site-packages/supertokens_python/recipe/session/recipe_implementation.py", line 151, in validate_claims
    invalid_claims = await validate_claims_in_payload(
                           └ <function validate_claims_in_payload at 0x107b52200>
  File "../site-packages/supertokens_python/recipe/session/utils.py", line 512, in validate_claims_in_payload
    json.dumps(claim_validation_res.__dict__),
    │    │     │                    └ <attribute '__dict__' of 'ClaimValidationResult' objects>
    │    │     └ <supertokens_python.recipe.session.interfaces.ClaimValidationResult object at 0x12c8b0df0>
    │    └ <function dumps at 0x1048cd090>
    └ <module 'json' from '/Users/omerzuarets/.pyenv/versions/3.10.5/lib/python3.10/json/__init__.py'>
  File "../json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           │                │      └ {'is_valid': False, 'reason': {'message': 'wrong value', 'expectedValue': <class 'str'>, 'actualValue': '92afae68-5bbd-4325-b...
           │                └ <function JSONEncoder.encode at 0x1048cd3f0>
           └ <json.encoder.JSONEncoder object at 0x1048a30a0>
  File "../json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
             │    │          └ {'is_valid': False, 'reason': {'message': 'wrong value', 'expectedValue': <class 'str'>, 'actualValue': '92afae68-5bbd-4325-b...
             │    └ <function JSONEncoder.iterencode at 0x1048cd480>
             └ <json.encoder.JSONEncoder object at 0x1048a30a0>
  File "../json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
           │           └ {'is_valid': False, 'reason': {'message': 'wrong value', 'expectedValue': <class 'str'>, 'actualValue': '92afae68-5bbd-4325-b...
           └ <_json.Encoder object at 0x1196f1d20>
  File "../json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type type is not JSON serializable
```
The reason is that the expectedValue is <class str> 
2. For some reason the new_access_token_payload is:
```json
{
   "sub":"...",
   "exp":1686130120,
   "iat":...,
   "sessionHandle":"...",
   "refreshTokenHash1":"...",
   "parentRefreshTokenHash1":null,
   "antiCsrfToken":null,
   "iss":"http://localhost:8000/auth",
   "active_tenant":{
      "v":"92afae68-5bbd-4325-b819-c8d57c87b527",
      "t":1686126520815
   }
}
```
but the claim_validator_res is 
```json
{
   "actualValue":"92afae68-5bbd-4325-b819-c8d57c87b527",
   "expectedValue":"<class 'str'>",
   "message":"wrong value"
}
```

I guess both of them happen because of the same reason, I guess thats because of that line `TenantClaim.validators.has_value(str)`. I thought it supposed to have a "type" to validate, not an actual value.
If thats not the case, how do I validate that the TenantClaim has any string value ?

To clarify my use case:
I am building a multi-tenancy application, I want to make sure any logged in user have an `active_tenant` in his claims, I need it because I use that `active_tenant` in my authorization checks and in my database queries, I don't really care whats in there because other parts of my system will make sure the value is valid.

**Comment by rishabhpoddar** [comment] 2023-06-09 05:46
Since this is not a bug in our SDK, i am closing this issue.

**Closed by rishabhpoddar** 2023-06-09 05:46 UTC

**Comment by rishabhpoddar** [comment] 2023-06-09 10:38
> It would be nice to contribute it to this repo but I don't have the permissions to do this..

You could fork the repo and create a PR. But i don't think we want to add this function to the primitive claim anyway.
